use std::collections::{BTreeMap, HashSet};

use serde::{Deserialize, Serialize};

use super::types::{
    EvidenceKind, EvidenceSignal, EvidenceVerdict, ExperienceCategory, ExperienceMemory,
    ExperienceScope, FailureClass, OutcomeDimensions,
};

const MAX_STORED_TEXT_CHARS: usize = 240;
const MAX_COMMAND_CHARS: usize = 180;
const MAX_REDACTED_TEXT_CHARS: usize = 8_192;
const MAX_KEY_DECISIONS: usize = 8;
const MAX_OBSERVED_EVENTS: usize = 128;
const MAX_FAILURE_LESSONS: usize = 4;
const MAX_VERIFICATION_LESSONS: usize = 3;

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Default)]
#[serde(default)]
pub struct ObservedEvent {
    pub tool_name: String,
    pub command: Option<String>,
    pub output: String,
    pub exit_code: Option<i32>,
    pub succeeded: Option<bool>,
    pub timestamp: i64,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Default)]
#[serde(default)]
pub struct RunObservation {
    pub run_id: String,
    pub task_type: String,
    pub task_summary: String,
    pub repository_id: String,
    pub repository_revision: Option<String>,
    pub environment: String,
    pub strategy: String,
    pub strategy_rationale: String,
    pub key_decisions: Vec<String>,
    pub changed_paths: Vec<String>,
    pub events: Vec<ObservedEvent>,
    pub judge_feedback: Option<String>,
    pub user_feedback: Option<String>,
    pub completed: Option<bool>,
}

pub fn classify_failure(text: &str) -> Option<FailureClass> {
    let text = text.to_ascii_lowercase();

    if contains_any(
        &text,
        &[
            "database is locked",
            "database locked",
            "deadlock detected",
            "lock wait timeout",
            "could not obtain lock",
            "lock contention",
            "sqlite_busy",
        ],
    ) {
        return Some(FailureClass::DatabaseLock);
    }

    if contains_any(
        &text,
        &[
            "generated file",
            "generated code",
            "generated source",
            "automatically generated",
            "auto-generated",
            "autogenerated",
            "do not edit",
            "overwritten during build",
        ],
    ) {
        return Some(FailureClass::GeneratedFile);
    }

    if contains_any(
        &text,
        &[
            "regression detected",
            "regression failure",
            "introduced a regression",
            "regression test failed",
            "performance regression",
        ],
    ) {
        return Some(FailureClass::Regression);
    }

    if contains_any(
        &text,
        &[
            "permission denied",
            "operation not permitted",
            "access denied",
            "forbidden",
            "eacces",
            "unauthorized",
        ],
    ) {
        return Some(FailureClass::Permission);
    }

    if contains_any(
        &text,
        &[
            "timed out",
            "timeout exceeded",
            "deadline exceeded",
            "operation timeout",
            "request timeout",
        ],
    ) {
        return Some(FailureClass::Timeout);
    }

    if contains_any(
        &text,
        &[
            "dependency resolution",
            "failed to select a version",
            "could not resolve dependency",
            "unable to resolve dependency",
            "module not found",
            "cannot find module",
            "no matching package",
            "package not found",
            "unresolved import",
        ],
    ) {
        return Some(FailureClass::Dependency);
    }

    if contains_any(
        &text,
        &[
            "type mismatch",
            "type error",
            "typecheck failed",
            "type check failed",
            "incompatible types",
            "is not assignable to type",
            "error ts",
            "mypy:",
        ],
    ) {
        return Some(FailureClass::TypeCheck);
    }

    if contains_any(
        &text,
        &[
            "lint failed",
            "lint error",
            "linting failed",
            "clippy::",
            "eslint error",
            "ruff failed",
        ],
    ) {
        return Some(FailureClass::Lint);
    }

    if contains_any(
        &text,
        &[
            "test failed",
            "tests failed",
            "failing test",
            "failed test",
            "test result: failed",
            "failures:",
            "assertion failed",
            "assertionerror",
            "assertionerror:",
            "panicked at",
        ],
    ) {
        return Some(FailureClass::Test);
    }

    if contains_any(
        &text,
        &[
            "build failed",
            "compilation failed",
            "compile error",
            "compiler error",
            "could not compile",
            "error[e",
            "build error",
        ],
    ) {
        return Some(FailureClass::Build);
    }

    None
}

pub fn classify_tool_evidence(event: &ObservedEvent) -> Option<EvidenceSignal> {
    let tool_name = event.tool_name.to_ascii_lowercase();

    if !matches!(
        tool_name.as_str(),
        "run_terminal_command"
            | "run_terminal_cmd"
            | "exec_command"
            | "run_command"
            | "bash"
            | "shell"
            | "judge"
            | "evaluator"
            | "external_judge"
            | "external_evaluator"
    ) {
        return None;
    }

    let verdict = event_verdict(event)?;
    let kind = classify_evidence_kind(event);
    let command = event
        .command
        .as_deref()
        .map(|command| sanitize_text(command, MAX_COMMAND_CHARS))
        .filter(|command| !command.is_empty());
    let summary = summarize_output(event, verdict);
    let score = if kind == EvidenceKind::Test {
        test_result_score(&event.output).or(match verdict {
            EvidenceVerdict::Passed => Some(1.0),
            EvidenceVerdict::Failed => Some(0.0),
            EvidenceVerdict::Neutral => None,
        })
    } else {
        match verdict {
            EvidenceVerdict::Passed => Some(1.0),
            EvidenceVerdict::Failed => Some(0.0),
            EvidenceVerdict::Neutral => None,
        }
    };

    Some(EvidenceSignal {
        kind,
        verdict,
        command,
        summary,
        score,
        observed_at: event.timestamp,
        source_run_id: None,
    })
}

pub fn extract_experiences(observation: &RunObservation) -> Vec<ExperienceMemory> {
    let source_run_id = sanitize_text(&observation.run_id, MAX_COMMAND_CHARS);
    let mut evidence: Vec<EvidenceSignal> = observation
        .events
        .iter()
        .skip(observation.events.len().saturating_sub(MAX_OBSERVED_EVENTS))
        .filter_map(classify_tool_evidence)
        .map(|mut signal| {
            signal.source_run_id = (!source_run_id.is_empty()).then(|| source_run_id.clone());
            signal
        })
        .collect();

    if !evidence.iter().any(EvidenceSignal::is_objective) {
        return Vec::new();
    }

    evidence.sort_by_key(|signal| signal.observed_at);
    let now = evidence
        .iter()
        .map(|signal| signal.observed_at)
        .max()
        .unwrap_or_default();
    let scope = observation_scope(&observation.changed_paths);
    let mut memories = Vec::new();
    let mut seen_failures = HashSet::new();

    for signal in evidence
        .iter()
        .filter(|signal| signal.verdict == EvidenceVerdict::Failed)
    {
        let failure_class = failure_class_for_signal(signal);

        if !seen_failures.insert(failure_class) {
            continue;
        }

        memories.push(build_failure_memory(
            observation,
            signal,
            failure_class,
            scope,
            now,
        ));

        if failure_class == FailureClass::GeneratedFile && proves_generated_file_behavior(signal) {
            memories.push(build_environmental_fact(observation, signal, now));
        }

        if seen_failures.len() >= MAX_FAILURE_LESSONS {
            break;
        }
    }

    let mut seen_verifications = HashSet::new();

    for signal in evidence
        .iter()
        .filter(|signal| signal.verdict == EvidenceVerdict::Passed && signal.is_verification())
    {
        let verification_key = format!(
            "{:?}:{}",
            signal.kind,
            signal.command.as_deref().unwrap_or_default()
        );

        if !seen_verifications.insert(verification_key) {
            continue;
        }

        memories.push(build_verification_memory(observation, signal, now));

        if seen_verifications.len() >= MAX_VERIFICATION_LESSONS {
            break;
        }
    }

    if let Some(signal) = evidence.iter().find(|signal| {
        signal.is_objective()
            && signal.verdict == EvidenceVerdict::Passed
            && proves_architectural_boundary(signal)
    }) {
        memories.push(build_architectural_lesson(observation, signal, now));
    }

    if let Some(conflicting_signals) = unresolved_objective_contradiction(&evidence) {
        memories.push(build_uncertain_hypothesis(
            observation,
            &conflicting_signals,
            now,
        ));
    }

    if should_extract_successful_pattern(observation, &evidence) {
        memories.push(build_successful_pattern(observation, &evidence, scope, now));
    }

    memories
}

fn event_verdict(event: &ObservedEvent) -> Option<EvidenceVerdict> {
    if event.exit_code.is_some_and(|exit_code| exit_code != 0) || event.succeeded == Some(false) {
        return Some(EvidenceVerdict::Failed);
    }

    if event.exit_code == Some(0) || event.succeeded == Some(true) {
        return Some(EvidenceVerdict::Passed);
    }

    None
}

fn classify_evidence_kind(event: &ObservedEvent) -> EvidenceKind {
    let command = event
        .command
        .as_deref()
        .unwrap_or_default()
        .to_ascii_lowercase();
    let tool_name = event.tool_name.to_ascii_lowercase();
    let output = event.output.to_ascii_lowercase();
    let command_and_tool = format!("{command} {tool_name}");

    if matches!(
        tool_name.as_str(),
        "judge" | "evaluator" | "external_judge" | "external_evaluator"
    ) {
        return EvidenceKind::Judge;
    }

    if contains_any(
        &command_and_tool,
        &[
            "regression",
            "cargo test",
            " test ",
            "benchmark",
            "cargo bench",
        ],
    ) && contains_any(
        &output,
        &[
            "regression detected",
            "performance regression",
            "introduced a regression",
        ],
    ) {
        return EvidenceKind::Regression;
    }

    if contains_any(
        &command_and_tool,
        &["benchmark", "cargo bench", "hyperfine"],
    ) {
        return EvidenceKind::Benchmark;
    }

    if contains_any(
        &command_and_tool,
        &[
            "clippy",
            "eslint",
            "ruff",
            "flake8",
            "golangci-lint",
            " lint",
        ],
    ) {
        return EvidenceKind::Lint;
    }

    if contains_any(
        &command_and_tool,
        &[
            "typecheck",
            "type-check",
            "mypy",
            "pyright",
            "tsc ",
            "tsc --",
        ],
    ) {
        return EvidenceKind::TypeCheck;
    }

    if contains_any(
        &command_and_tool,
        &[
            "cargo test",
            "cargo nextest",
            "pytest",
            "jest",
            "vitest",
            "go test",
            "npm test",
            "npm run test",
            "pnpm test",
            "yarn test",
            "gradle test",
            "mvn test",
            " test ",
            "test_runner",
        ],
    ) {
        return EvidenceKind::Test;
    }

    if contains_any(
        &command_and_tool,
        &[
            "cargo build",
            "cargo check",
            "rustc",
            "gradle assemble",
            "npm run build",
            "pnpm build",
            " compile",
            "make ",
        ],
    ) {
        return EvidenceKind::Compile;
    }

    if contains_any(&command_and_tool, &["git diff", "diff --check"]) {
        return EvidenceKind::Diff;
    }

    if contains_any(&command_and_tool, &["runtime", "integration_run"]) {
        return EvidenceKind::Runtime;
    }

    EvidenceKind::CommandExit
}

fn summarize_output(event: &ObservedEvent, verdict: EvidenceVerdict) -> String {
    let preferred_line = event
        .output
        .lines()
        .map(str::trim)
        .filter(|line| !line.is_empty())
        .find(|line| {
            let line = line.to_ascii_lowercase();
            classify_failure(&line).is_some()
                || contains_any(
                    &line,
                    &[
                        "test result:",
                        "error:",
                        "failed",
                        "passed",
                        "build successful",
                        "exit code:",
                    ],
                )
        })
        .or_else(|| {
            event
                .output
                .lines()
                .map(str::trim)
                .find(|line| !line.is_empty())
        });

    if let Some(line) = preferred_line {
        return sanitize_text(line, MAX_STORED_TEXT_CHARS);
    }

    match (event.exit_code, verdict) {
        (Some(exit_code), _) => format!("Command exited with status {exit_code}"),
        (_, EvidenceVerdict::Passed) => "Tool reported successful completion".to_string(),
        (_, EvidenceVerdict::Failed) => "Tool reported unsuccessful completion".to_string(),
        (_, EvidenceVerdict::Neutral) => "Tool produced inconclusive evidence".to_string(),
    }
}

fn test_result_score(output: &str) -> Option<f64> {
    let mut previous_number = None;
    let mut passed = None;
    let mut failed = None;

    for token in output.split(|character: char| !character.is_ascii_alphanumeric()) {
        if token.is_empty() {
            continue;
        }

        if let Ok(number) = token.parse::<u64>() {
            previous_number = Some(number);
            continue;
        }

        match token.to_ascii_lowercase().as_str() {
            "passed" | "passing" => passed = previous_number,
            "failed" | "failing" => failed = previous_number,
            _ => {}
        }

        previous_number = None;
    }

    match (passed, failed) {
        (Some(passed), Some(failed)) if passed.saturating_add(failed) > 0 => {
            Some(passed as f64 / passed.saturating_add(failed) as f64)
        }
        _ => None,
    }
}

fn observation_scope(changed_paths: &[String]) -> ExperienceScope {
    let concrete_paths: Vec<&str> = changed_paths
        .iter()
        .map(String::as_str)
        .filter(|path| is_concrete_path(path))
        .collect();

    match concrete_paths.as_slice() {
        [] => ExperienceScope::Repository,
        [_] => ExperienceScope::ExactFile,
        [first, remaining @ ..] => {
            let first_parent = first.rsplit_once('/').map(|(parent, _)| parent);

            if first_parent.is_some()
                && remaining
                    .iter()
                    .all(|path| path.rsplit_once('/').map(|(parent, _)| parent) == first_parent)
            {
                ExperienceScope::Module
            } else {
                ExperienceScope::Repository
            }
        }
    }
}

fn is_concrete_path(path: &str) -> bool {
    let path = path.trim();

    !path.is_empty()
        && path != "."
        && path != ".."
        && !path.contains(['\n', '\r', '*', '?'])
        && std::path::Path::new(path)
            .file_name()
            .is_some_and(|name| !name.is_empty())
}

fn failure_class_for_signal(signal: &EvidenceSignal) -> FailureClass {
    let combined = format!(
        "{} {}",
        signal.command.as_deref().unwrap_or_default(),
        signal.summary
    );

    classify_failure(&combined).unwrap_or(match signal.kind {
        EvidenceKind::Test => FailureClass::Test,
        EvidenceKind::Compile => FailureClass::Build,
        EvidenceKind::Lint => FailureClass::Lint,
        EvidenceKind::TypeCheck => FailureClass::TypeCheck,
        EvidenceKind::Regression => FailureClass::Regression,
        _ => FailureClass::Unknown,
    })
}

fn build_failure_memory(
    observation: &RunObservation,
    signal: &EvidenceSignal,
    failure_class: FailureClass,
    scope: ExperienceScope,
    now: i64,
) -> ExperienceMemory {
    let lesson = failure_lesson(failure_class, signal);
    let mut memory = ExperienceMemory::new(
        ExperienceCategory::FailureAntiPattern,
        lesson.clone(),
        sanitize_text(&observation.run_id, MAX_COMMAND_CHARS),
        now,
    );
    let failure_scope = match failure_class {
        FailureClass::Build
        | FailureClass::Test
        | FailureClass::TypeCheck
        | FailureClass::Regression => scope,
        FailureClass::DatabaseLock
        | FailureClass::Lint
        | FailureClass::GeneratedFile
        | FailureClass::Permission
        | FailureClass::Timeout
        | FailureClass::Dependency
        | FailureClass::Unknown => ExperienceScope::Repository,
    };
    populate_common_fields(&mut memory, observation, failure_scope);
    memory.success = Some(false);
    memory.failure_reason = Some(signal.summary.clone());
    memory.what_failed = vec![signal.summary.clone()];
    memory.anti_pattern = Some(lesson.clone());
    memory.recommendation = Some(failure_recommendation(failure_class).to_string());
    memory.evidence = vec![signal.clone()];

    if signal.kind == EvidenceKind::Test {
        memory.tests_run = signal.command.iter().cloned().collect();
        memory.test_results = vec![signal.clone()];
        memory.outcome.functional_correctness = signal.score;
    }

    if matches!(
        failure_class,
        FailureClass::Build | FailureClass::TypeCheck | FailureClass::Regression
    ) {
        memory.outcome.functional_correctness = Some(0.0);
    }

    if failure_class == FailureClass::Regression {
        memory.outcome.regression_risk = Some(0.9);
    }

    memory.refresh_confidence();
    memory
}

fn failure_lesson(failure_class: FailureClass, signal: &EvidenceSignal) -> String {
    match failure_class {
        FailureClass::DatabaseLock => {
            "Avoid parallel database or migration operations when database lock contention is observed".to_string()
        }
        FailureClass::GeneratedFile => {
            "Avoid directly editing generated files; modify the generator or source inputs instead".to_string()
        }
        FailureClass::Permission => {
            "Avoid repeating an operation denied by the current permissions without changing its execution context".to_string()
        }
        FailureClass::Timeout => {
            "Avoid repeating an operation that exceeded its deadline without reducing or restructuring its workload".to_string()
        }
        FailureClass::Dependency => {
            "Resolve the observed dependency or module mismatch before repeating the same implementation strategy".to_string()
        }
        FailureClass::Regression => {
            "Avoid the change pattern associated with the observed regression until its compatibility boundary is understood".to_string()
        }
        _ => {
            let command = signal.command.as_deref().unwrap_or("the same operation");
            sanitize_text(
                &format!(
                    "Avoid repeating `{command}` unchanged after the observed failure: {}",
                    signal.summary
                ),
                MAX_STORED_TEXT_CHARS,
            )
        }
    }
}

fn failure_recommendation(failure_class: FailureClass) -> &'static str {
    match failure_class {
        FailureClass::DatabaseLock => "Serialize database changes or release the conflicting lock",
        FailureClass::Build => "Address the compiler diagnostics before rerunning the build",
        FailureClass::Test => {
            "Use the failing test as a focused reproduction before revising the implementation"
        }
        FailureClass::Lint => "Correct the reported lint violation before repeating validation",
        FailureClass::TypeCheck => "Resolve the reported type mismatch before repeating validation",
        FailureClass::GeneratedFile => {
            "Locate and update the generator, schema, or source template"
        }
        FailureClass::Permission => "Use an authorized operation or change the execution context",
        FailureClass::Timeout => {
            "Reduce the workload, serialize contention, or use a focused check"
        }
        FailureClass::Dependency => "Verify the dependency graph and available module versions",
        FailureClass::Regression => {
            "Reproduce the regression and preserve the existing compatibility boundary"
        }
        FailureClass::Unknown => {
            "Classify the observed failure before selecting a different strategy"
        }
    }
}

fn build_verification_memory(
    observation: &RunObservation,
    signal: &EvidenceSignal,
    now: i64,
) -> ExperienceMemory {
    let command = signal
        .command
        .as_deref()
        .unwrap_or("the focused verification");
    let lesson = sanitize_text(
        &format!(
            "Use `{command}` as an evidence-backed {} check",
            verification_label(signal.kind)
        ),
        MAX_STORED_TEXT_CHARS,
    );
    let mut memory = ExperienceMemory::new(
        ExperienceCategory::ToolProcessLesson,
        lesson.clone(),
        sanitize_text(&observation.run_id, MAX_COMMAND_CHARS),
        now,
    );
    populate_common_fields(&mut memory, observation, ExperienceScope::Repository);
    memory.success = Some(true);
    memory.recommendation = Some(lesson);
    memory.what_worked = vec![signal.summary.clone()];
    memory.evidence = vec![signal.clone()];

    if signal.kind == EvidenceKind::Test {
        memory.tests_run = signal.command.iter().cloned().collect();
        memory.test_results = vec![signal.clone()];
        memory.outcome.functional_correctness = signal.score;
    }

    memory.refresh_confidence();
    memory
}

fn proves_generated_file_behavior(signal: &EvidenceSignal) -> bool {
    let summary = signal.summary.to_ascii_lowercase();
    let identifies_generated_file = contains_any(
        &summary,
        &[
            "generated file",
            "generated code",
            "generated source",
            "automatically generated",
            "auto-generated",
            "autogenerated",
        ],
    );
    let establishes_generated_behavior = contains_any(
        &summary,
        &[
            "overwritten",
            "overwrote",
            "regenerated",
            "regenerate",
            "do not edit",
            "automatically generated",
            "auto-generated",
        ],
    );

    signal.is_objective()
        && signal.verdict == EvidenceVerdict::Failed
        && identifies_generated_file
        && establishes_generated_behavior
}

fn build_environmental_fact(
    observation: &RunObservation,
    signal: &EvidenceSignal,
    now: i64,
) -> ExperienceMemory {
    let summary = signal.summary.to_ascii_lowercase();
    let lesson = if contains_any(&summary, &["overwritten", "overwrote", "regenerated"]) {
        "Generated files in this repository can be overwritten or regenerated; update their generator inputs"
    } else {
        "This repository contains generated files that must be changed through their generator inputs"
    };
    let mut memory = ExperienceMemory::new(
        ExperienceCategory::EnvironmentalFact,
        lesson,
        sanitize_text(&observation.run_id, MAX_COMMAND_CHARS),
        now,
    );
    populate_common_fields(&mut memory, observation, ExperienceScope::Repository);
    memory.success = Some(false);
    memory.failure_reason = Some(signal.summary.clone());
    memory.recommendation = Some("Edit the generator, schema, or source template instead".into());
    memory.what_failed = vec![signal.summary.clone()];
    memory.evidence = vec![signal.clone()];
    memory.refresh_confidence();
    memory
}

fn proves_architectural_boundary(signal: &EvidenceSignal) -> bool {
    let summary = signal.summary.to_ascii_lowercase();

    signal.is_verification()
        && contains_any(
            &summary,
            &[
                "architectural boundary verified",
                "architecture boundary verified",
                "service boundary verified",
                "integration boundary verified",
                "boundary contract verified",
            ],
        )
}

fn build_architectural_lesson(
    observation: &RunObservation,
    signal: &EvidenceSignal,
    now: i64,
) -> ExperienceMemory {
    let lesson = sanitize_text(
        &format!(
            "Preserve the independently verified architectural boundary: {}",
            signal.summary
        ),
        MAX_STORED_TEXT_CHARS,
    );
    let mut memory = ExperienceMemory::new(
        ExperienceCategory::ArchitecturalLesson,
        lesson.clone(),
        sanitize_text(&observation.run_id, MAX_COMMAND_CHARS),
        now,
    );
    populate_common_fields(&mut memory, observation, ExperienceScope::Repository);
    memory.success = Some(true);
    memory.recommendation = Some(lesson);
    memory.what_worked = vec![signal.summary.clone()];
    memory.evidence = vec![signal.clone()];
    memory.refresh_confidence();
    memory
}

fn unresolved_objective_contradiction(evidence: &[EvidenceSignal]) -> Option<Vec<EvidenceSignal>> {
    let mut by_command: BTreeMap<String, Vec<&EvidenceSignal>> = BTreeMap::new();

    for signal in evidence.iter().filter(|signal| signal.is_objective()) {
        let Some(command) = signal
            .command
            .as_deref()
            .filter(|command| !command.is_empty())
        else {
            continue;
        };
        let key = format!("{:?}:{command}", signal.kind);
        by_command.entry(key).or_default().push(signal);
    }

    by_command.into_values().find_map(|signals| {
        let final_verdict = signals.last().map(|signal| signal.verdict);
        let has_success = signals
            .iter()
            .any(|signal| signal.verdict == EvidenceVerdict::Passed);

        if final_verdict == Some(EvidenceVerdict::Failed) && has_success {
            Some(signals.into_iter().take(4).cloned().collect())
        } else {
            None
        }
    })
}

fn build_uncertain_hypothesis(
    observation: &RunObservation,
    signals: &[EvidenceSignal],
    now: i64,
) -> ExperienceMemory {
    let command = signals
        .first()
        .and_then(|signal| signal.command.as_deref())
        .unwrap_or("the observed verification");
    let lesson = sanitize_text(
        &format!(
            "Conflicting objective results for `{command}` remain unresolved; reproduce the discrepancy before relying on this approach"
        ),
        MAX_STORED_TEXT_CHARS,
    );
    let mut memory = ExperienceMemory::new(
        ExperienceCategory::UncertainHypothesis,
        lesson.clone(),
        sanitize_text(&observation.run_id, MAX_COMMAND_CHARS),
        now,
    );
    populate_common_fields(&mut memory, observation, ExperienceScope::Repository);
    memory.recommendation = Some(lesson);
    memory.evidence = signals.to_vec();
    memory.refresh_confidence();
    memory
}

fn verification_label(kind: EvidenceKind) -> &'static str {
    match kind {
        EvidenceKind::Test => "test",
        EvidenceKind::Compile => "compilation",
        EvidenceKind::Lint => "lint",
        EvidenceKind::TypeCheck => "type-checking",
        EvidenceKind::Benchmark => "benchmark",
        EvidenceKind::Regression => "regression",
        EvidenceKind::Diff => "diff-quality",
        _ => "verification",
    }
}

fn should_extract_successful_pattern(
    observation: &RunObservation,
    evidence: &[EvidenceSignal],
) -> bool {
    if observation.completed != Some(true) || observation.strategy.trim().is_empty() {
        return false;
    }

    if !evidence.iter().any(|signal| {
        matches!(
            signal.kind,
            EvidenceKind::Test
                | EvidenceKind::Compile
                | EvidenceKind::TypeCheck
                | EvidenceKind::Runtime
                | EvidenceKind::Regression
        ) && signal.verdict == EvidenceVerdict::Passed
    }) {
        return false;
    }

    if observation
        .judge_feedback
        .as_deref()
        .is_some_and(is_negative_feedback)
        || observation
            .user_feedback
            .as_deref()
            .is_some_and(is_negative_feedback)
    {
        return false;
    }

    let mut latest_verdicts = BTreeMap::new();

    for signal in evidence.iter().filter(|signal| signal.is_objective()) {
        let key = format!(
            "{:?}:{}",
            signal.kind,
            signal.command.as_deref().unwrap_or_default()
        );
        latest_verdicts.insert(key, signal.verdict);
    }

    !latest_verdicts
        .values()
        .any(|verdict| *verdict == EvidenceVerdict::Failed)
}

fn build_successful_pattern(
    observation: &RunObservation,
    evidence: &[EvidenceSignal],
    scope: ExperienceScope,
    now: i64,
) -> ExperienceMemory {
    let strategy = sanitize_text(&observation.strategy, MAX_STORED_TEXT_CHARS);
    let lesson = sanitize_text(
        &format!(
            "For similar {} work, consider the verified approach: {strategy}",
            task_label(observation)
        ),
        MAX_STORED_TEXT_CHARS,
    );
    let mut memory = ExperienceMemory::new(
        ExperienceCategory::SuccessfulPattern,
        lesson.clone(),
        sanitize_text(&observation.run_id, MAX_COMMAND_CHARS),
        now,
    );
    populate_common_fields(&mut memory, observation, scope);
    memory.success = Some(true);
    memory.implementation_pattern = Some(strategy);
    memory.recommendation = Some(lesson);
    memory.evidence = evidence
        .iter()
        .filter(|signal| signal.verdict == EvidenceVerdict::Passed && signal.is_objective())
        .take(MAX_VERIFICATION_LESSONS + 1)
        .cloned()
        .collect();
    memory.tests_run = memory
        .evidence
        .iter()
        .filter(|signal| signal.kind == EvidenceKind::Test)
        .filter_map(|signal| signal.command.clone())
        .collect();
    memory.test_results = memory
        .evidence
        .iter()
        .filter(|signal| signal.kind == EvidenceKind::Test)
        .cloned()
        .collect();
    memory.what_worked = memory
        .evidence
        .iter()
        .map(|signal| signal.summary.clone())
        .collect();
    memory.outcome = OutcomeDimensions {
        functional_correctness: memory
            .test_results
            .iter()
            .filter_map(|signal| signal.score)
            .reduce(f64::min),
        ..OutcomeDimensions::default()
    };
    memory.refresh_confidence();
    memory
}

fn populate_common_fields(
    memory: &mut ExperienceMemory,
    observation: &RunObservation,
    scope: ExperienceScope,
) {
    memory.task_type = sanitize_text(&observation.task_type, MAX_COMMAND_CHARS);
    memory.task_summary = sanitize_text(&observation.task_summary, MAX_STORED_TEXT_CHARS);
    memory.environment = sanitize_text(&observation.environment, MAX_COMMAND_CHARS);
    memory.repository_id = sanitize_text(&observation.repository_id, MAX_COMMAND_CHARS);
    memory.repository_revision = observation
        .repository_revision
        .as_deref()
        .map(|revision| sanitize_text(revision, MAX_COMMAND_CHARS));
    memory.scope = scope;
    memory.strategy = sanitize_text(&observation.strategy, MAX_STORED_TEXT_CHARS);
    memory.strategy_rationale =
        sanitize_text(&observation.strategy_rationale, MAX_STORED_TEXT_CHARS);
    memory.key_decisions = observation
        .key_decisions
        .iter()
        .take(MAX_KEY_DECISIONS)
        .map(|decision| sanitize_text(decision, MAX_STORED_TEXT_CHARS))
        .collect();
    memory.context = observation
        .changed_paths
        .iter()
        .filter(|path| is_concrete_path(path))
        .take(MAX_KEY_DECISIONS)
        .map(|path| sanitize_text(path, MAX_COMMAND_CHARS))
        .collect::<Vec<_>>()
        .join(", ");
    memory.judge_feedback = observation
        .judge_feedback
        .as_deref()
        .map(|feedback| sanitize_text(feedback, MAX_STORED_TEXT_CHARS));
    memory.generalizability = match scope {
        ExperienceScope::ExactFile => 0.1,
        ExperienceScope::Module => 0.2,
        ExperienceScope::Repository => 0.3,
        ExperienceScope::Framework => 0.4,
        ExperienceScope::TaskType => 0.45,
        ExperienceScope::Global => 0.5,
    };
}

fn task_label(observation: &RunObservation) -> String {
    if observation.task_type.trim().is_empty() {
        "repository".to_string()
    } else {
        sanitize_text(&observation.task_type, MAX_COMMAND_CHARS)
    }
}

fn is_negative_feedback(feedback: &str) -> bool {
    let feedback = feedback.to_ascii_lowercase();

    contains_any(
        &feedback,
        &[
            "rejected",
            "request changes",
            "changes requested",
            "incorrect",
            "poor quality",
            "regression",
            "does not work",
            "doesn't work",
            "not acceptable",
        ],
    )
}

fn sanitize_text(input: &str, max_chars: usize) -> String {
    truncate_chars(&redact_sensitive_text(input), max_chars)
}

pub(crate) fn is_sensitive_field_name(field: &str) -> bool {
    let normalized = field
        .trim()
        .chars()
        .map(|character| match character {
            '-' | '.' | ' ' => '_',
            _ => character.to_ascii_lowercase(),
        })
        .collect::<String>();
    let compact = normalized.replace('_', "");

    matches!(
        compact.as_str(),
        "awssecretaccesskey"
            | "awsaccesskeyid"
            | "awssessiontoken"
            | "awssecuritytoken"
            | "secretaccesskey"
            | "accesskeyid"
            | "sessiontoken"
            | "securitytoken"
    ) || matches!(
        normalized.as_str(),
        "token"
            | "secret"
            | "credential"
            | "credentials"
            | "password"
            | "passwd"
            | "api_key"
            | "apikey"
            | "authorization"
            | "cookie"
            | "set_cookie"
            | "session"
            | "sessionid"
            | "session_id"
            | "csrf"
            | "csrf_token"
            | "csrftoken"
            | "private_key"
    ) || [
        "_token",
        "_secret",
        "_credential",
        "_credentials",
        "_password",
        "_passwd",
        "_api_key",
        "_apikey",
        "_authorization",
        "_cookie",
        "_private_key",
    ]
    .iter()
    .any(|suffix| normalized.ends_with(suffix))
        || [
            "token_",
            "secret_",
            "credential_",
            "credentials_",
            "password_",
        ]
        .iter()
        .any(|prefix| normalized.starts_with(prefix))
        || [
            "token",
            "secret",
            "credential",
            "credentials",
            "password",
            "apikey",
            "authorization",
            "privatekey",
        ]
        .iter()
        .any(|suffix| normalized.ends_with(suffix))
}

pub(crate) fn redact_sensitive_text(input: &str) -> String {
    let without_private_keys = redact_private_key_blocks(input);
    let without_structured_secrets = redact_structured_secret_values(&without_private_keys);
    let without_secret_assignments = redact_secret_assignments(&without_structured_secrets);
    let mut sanitized = Vec::new();
    let mut redact_next = false;

    for raw_token in without_secret_assignments.split_whitespace() {
        let token = redact_url_credentials(raw_token);
        let normalized = token
            .trim_matches(|character: char| {
                matches!(character, '"' | '\'' | ',' | ';' | '(' | ')' | '[' | ']')
            })
            .to_ascii_lowercase();

        if redact_next {
            if normalized == "bearer" {
                sanitized.push(token.clone());
            } else {
                sanitized.push("[REDACTED]".to_string());
                redact_next = false;
            }

            continue;
        }

        if is_secret_flag(&normalized) {
            sanitized.push(token.clone());
            redact_next = true;
            continue;
        }

        let original_lowercase = token.to_ascii_lowercase();

        if let Some(position) = secret_assignment_position(&original_lowercase) {
            let assignment_end = position
                + original_lowercase[position..]
                    .find('=')
                    .map_or(0, |offset| offset + 1);
            sanitized.push(format!(
                "{}[REDACTED]",
                token.get(..assignment_end).unwrap_or_default()
            ));
            continue;
        }

        if looks_like_secret(&normalized) {
            sanitized.push("[REDACTED]".to_string());
            continue;
        }

        sanitized.push(token);
    }

    truncate_chars(&sanitized.join(" "), MAX_REDACTED_TEXT_CHARS)
}

fn redact_private_key_blocks(input: &str) -> String {
    let mut output = String::with_capacity(input.len().min(MAX_REDACTED_TEXT_CHARS));
    let mut remaining = input;

    while let Some(begin_offset) = remaining.find("-----BEGIN ") {
        output.push_str(&remaining[..begin_offset]);
        let after_begin = &remaining[begin_offset + "-----BEGIN ".len()..];
        let Some(header_end) = after_begin.find("-----") else {
            output.push_str("[REDACTED PRIVATE KEY]");
            return output;
        };
        let label = &after_begin[..header_end];

        if !label.to_ascii_uppercase().contains("PRIVATE KEY") {
            let marker_end = begin_offset + "-----BEGIN ".len() + header_end + "-----".len();
            output.push_str(&remaining[begin_offset..marker_end]);
            remaining = &remaining[marker_end..];
            continue;
        }

        let closing_marker = format!("-----END {label}-----");
        output.push_str("[REDACTED PRIVATE KEY]");

        if let Some(end_offset) = after_begin.find(&closing_marker) {
            remaining = &after_begin[end_offset + closing_marker.len()..];
        } else {
            return output;
        }
    }

    output.push_str(remaining);
    output
}

fn redact_structured_secret_values(input: &str) -> String {
    let mut output = String::with_capacity(input.len().min(MAX_REDACTED_TEXT_CHARS));
    let mut cursor = 0;

    while cursor < input.len() {
        let Some(key_start) = input[cursor..]
            .find(['"', '\''])
            .map(|offset| cursor + offset)
        else {
            output.push_str(&input[cursor..]);
            break;
        };
        let quote = input.as_bytes()[key_start];
        let key_content_end = quoted_value_end(input, key_start + 1, quote);

        if key_content_end >= input.len() {
            output.push_str(&input[cursor..]);
            break;
        }

        let key_end = key_content_end + 1;

        output.push_str(&input[cursor..key_end]);
        let after_key = skip_ascii_whitespace(input, key_end);

        if !is_sensitive_field_name(&input[key_start + 1..key_content_end])
            || !matches!(input.as_bytes().get(after_key), Some(b':' | b'='))
        {
            cursor = key_end;
            continue;
        }

        let value_start = skip_ascii_whitespace(input, after_key + 1);
        output.push_str(&input[key_end..value_start]);

        let Some(&first_byte) = input.as_bytes().get(value_start) else {
            break;
        };

        if first_byte == b'"' || first_byte == b'\'' {
            output.push(first_byte as char);
            let value_end = quoted_value_end(input, value_start + 1, first_byte);
            output.push_str("[REDACTED]");

            if value_end < input.len() {
                output.push(first_byte as char);
                cursor = value_end + 1;
            } else {
                cursor = value_end;
            }
        } else {
            let value_end = structured_value_end(input, value_start);
            output.push_str("[REDACTED]");
            cursor = value_end;
        }
    }

    output
}

fn redact_secret_assignments(input: &str) -> String {
    let mut output = String::with_capacity(input.len().min(MAX_REDACTED_TEXT_CHARS));
    let mut cursor = 0;

    while let Some(offset) = input[cursor..].find('=') {
        let assignment = cursor + offset;
        let field_start = input[..assignment]
            .char_indices()
            .rev()
            .find(|(_, character)| {
                !character.is_ascii_alphanumeric() && !matches!(character, '_' | '-' | '.')
            })
            .map_or(0, |(index, character)| index + character.len_utf8());
        let field = input[field_start..assignment].trim_start_matches('-');

        if !is_sensitive_field_name(field) {
            output.push_str(&input[cursor..assignment + 1]);
            cursor = assignment + 1;
            continue;
        }

        let value_start = assignment + 1;
        output.push_str(&input[cursor..value_start]);

        match input.as_bytes().get(value_start).copied() {
            Some(quote @ (b'"' | b'\'')) => {
                output.push(quote as char);
                output.push_str("[REDACTED]");
                let value_end = quoted_value_end(input, value_start + 1, quote);

                if value_end < input.len() {
                    output.push(quote as char);
                    cursor = value_end + 1;
                } else {
                    cursor = value_end;
                }
            }
            Some(_) => {
                let value_end = input[value_start..]
                    .find(|character: char| {
                        character.is_whitespace()
                            || matches!(character, ',' | ';' | '&' | '}' | ']')
                    })
                    .map_or(input.len(), |offset| value_start + offset);
                output.push_str("[REDACTED]");
                cursor = value_end;
            }
            None => cursor = value_start,
        }
    }

    output.push_str(&input[cursor..]);
    output
}

fn structured_value_end(text: &str, start: usize) -> usize {
    if !matches!(text.as_bytes().get(start), Some(b'{' | b'[')) {
        return text[start..]
            .find(|character: char| {
                character.is_whitespace() || matches!(character, ',' | ';' | '}' | ']' | '&')
            })
            .map_or(text.len(), |offset| start + offset);
    }

    let bytes = text.as_bytes();
    let mut cursor = start;
    let mut depth = 0_usize;

    while let Some(&byte) = bytes.get(cursor) {
        match byte {
            b'"' | b'\'' => {
                cursor = quoted_value_end(text, cursor + 1, byte);
            }
            b'{' | b'[' => depth += 1,
            b'}' | b']' => {
                depth = depth.saturating_sub(1);

                if depth == 0 {
                    return cursor + 1;
                }
            }
            _ => {}
        }

        cursor += 1;
    }

    text.len()
}

fn skip_ascii_whitespace(text: &str, mut cursor: usize) -> usize {
    while text
        .as_bytes()
        .get(cursor)
        .is_some_and(u8::is_ascii_whitespace)
    {
        cursor += 1;
    }

    cursor
}

fn quoted_value_end(text: &str, mut cursor: usize, quote: u8) -> usize {
    let bytes = text.as_bytes();

    while let Some(&byte) = bytes.get(cursor) {
        if byte == b'\\' {
            cursor = cursor.saturating_add(2);
        } else if byte == quote {
            return cursor;
        } else {
            cursor += 1;
        }
    }

    text.len()
}

fn redact_url_credentials(token: &str) -> String {
    let Some(scheme_end) = token.find("://") else {
        return token.to_string();
    };
    let authority_start = scheme_end + "://".len();
    let authority_end = token[authority_start..]
        .find(['/', '?', '#', '"', '\'', ' ', ','])
        .map_or(token.len(), |offset| authority_start + offset);
    let authority = &token[authority_start..authority_end];
    let Some(userinfo_end) = authority.rfind('@') else {
        return token.to_string();
    };

    format!(
        "{}[REDACTED]@{}",
        &token[..authority_start],
        &token[authority_start + userinfo_end + 1..]
    )
}

fn is_secret_flag(token: &str) -> bool {
    matches!(
        token,
        "bearer"
            | "authorization:"
            | "authorization"
            | "api_key:"
            | "apikey:"
            | "api-key:"
            | "token:"
            | "access_token:"
            | "refresh_token:"
            | "password:"
            | "secret:"
            | "cookie:"
            | "set-cookie:"
            | "--cookie"
            | "--header-cookie"
            | "-b"
            | "--token"
            | "--api-key"
            | "--apikey"
            | "--password"
            | "--secret"
            | "--credential"
            | "--credentials"
    ) || token.strip_suffix(':').is_some_and(is_sensitive_field_name)
        || token
            .strip_prefix("--")
            .is_some_and(is_sensitive_field_name)
}

fn secret_assignment_position(token: &str) -> Option<usize> {
    let legacy_position = [
        "api_key=",
        "apikey=",
        "api-key=",
        "access_token=",
        "refresh_token=",
        "token=",
        "credential=",
        "credentials=",
        "cookie=",
        "session=",
        "sessionid=",
        "session_id=",
        "csrf=",
        "csrf_token=",
        "csrftoken=",
        "password=",
        "passwd=",
        "secret=",
        "authorization=",
    ]
    .iter()
    .filter_map(|marker| token.find(marker))
    .min();
    let sensitive_position = token.match_indices('=').find_map(|(assignment, _)| {
        let field_start = token[..assignment]
            .char_indices()
            .rev()
            .find(|(_, character)| {
                !character.is_ascii_alphanumeric() && !matches!(character, '_' | '-' | '.')
            })
            .map_or(0, |(index, character)| index + character.len_utf8());
        let field = token[field_start..assignment].trim_start_matches('-');

        is_sensitive_field_name(field).then_some(field_start)
    });

    match (legacy_position, sensitive_position) {
        (Some(legacy), Some(sensitive)) => Some(legacy.min(sensitive)),
        (Some(position), None) | (None, Some(position)) => Some(position),
        (None, None) => None,
    }
}

fn looks_like_secret(token: &str) -> bool {
    let token = token.trim_start_matches(['"', '\'', '=', ':']);

    token.starts_with("sk-")
        || token.starts_with("sk_")
        || (token.starts_with("xai-") && !token.starts_with("xai-grok") && token.len() >= 24)
        || token.starts_with("ghp_")
        || token.starts_with("gho_")
        || token.starts_with("ghs_")
        || token.starts_with("github_pat_")
        || token.starts_with("glpat-")
        || (token.starts_with("akia") && token.len() >= 16)
        || (token.len() > 32
            && token.split('.').count() == 3
            && token.split('.').all(|segment| {
                segment.len() >= 8
                    && segment.chars().all(|character| {
                        character.is_ascii_alphanumeric() || matches!(character, '-' | '_')
                    })
            }))
}

fn truncate_chars(input: &str, max_chars: usize) -> String {
    if max_chars == 0 {
        return String::new();
    }

    let mut characters = input.chars();
    let mut output: String = characters.by_ref().take(max_chars).collect();

    if characters.next().is_some() {
        output.pop();
        output.push('…');
    }

    output
}

fn contains_any(text: &str, patterns: &[&str]) -> bool {
    patterns.iter().any(|pattern| text.contains(pattern))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn event(command: &str, output: &str, exit_code: i32, timestamp: i64) -> ObservedEvent {
        ObservedEvent {
            tool_name: "run_terminal_command".to_string(),
            command: Some(command.to_string()),
            output: output.to_string(),
            exit_code: Some(exit_code),
            succeeded: None,
            timestamp,
        }
    }

    fn observation(events: Vec<ObservedEvent>) -> RunObservation {
        RunObservation {
            run_id: "run-42".to_string(),
            task_type: "parser change".to_string(),
            task_summary: "Extend parser visitor".to_string(),
            repository_id: "repo-7".to_string(),
            repository_revision: Some("abc123".to_string()),
            environment: "rust-1.94".to_string(),
            strategy: "Extend the existing AST visitor".to_string(),
            strategy_rationale: "Preserve existing parser boundaries".to_string(),
            key_decisions: vec!["Reuse the visitor extension point".to_string()],
            changed_paths: vec!["src/parser/visitor.rs".to_string()],
            events,
            judge_feedback: None,
            user_feedback: None,
            completed: Some(true),
        }
    }

    #[test]
    fn run_observations_deserialize_missing_legacy_fields() {
        let observation: RunObservation = serde_json::from_str(r#"{"run_id":"old-run"}"#).unwrap();
        let event: ObservedEvent = serde_json::from_str(r#"{"tool_name":"bash"}"#).unwrap();

        assert_eq!(observation.run_id, "old-run");
        assert!(observation.events.is_empty());
        assert_eq!(event.exit_code, None);
        assert_eq!(event.succeeded, None);
    }

    #[test]
    fn failure_classifier_prioritizes_specific_root_causes() {
        assert_eq!(
            classify_failure("migration test failed: database is locked"),
            Some(FailureClass::DatabaseLock)
        );
        assert_eq!(
            classify_failure("build failed: generated file is overwritten during build"),
            Some(FailureClass::GeneratedFile)
        );
        assert_eq!(
            classify_failure("test failed: performance regression detected"),
            Some(FailureClass::Regression)
        );
    }

    #[test]
    fn failure_classifier_covers_environment_and_validation_failures() {
        let cases = [
            ("permission denied", FailureClass::Permission),
            ("request timed out", FailureClass::Timeout),
            ("cannot find module foo", FailureClass::Dependency),
            ("type mismatch in callback", FailureClass::TypeCheck),
            ("lint failed: unused import", FailureClass::Lint),
            ("assertion failed: value changed", FailureClass::Test),
            ("error[E0308]: could not compile", FailureClass::Build),
        ];

        for (message, expected) in cases {
            assert_eq!(
                classify_failure(message),
                Some(expected),
                "message: {message}"
            );
        }

        assert_eq!(
            classify_failure("The assistant said the code worked well"),
            None
        );
    }

    #[test]
    fn explicit_exit_status_beats_optimistic_success_claim() {
        let mut failed = event("cargo test", "The implementation worked well", 1, 7);
        failed.succeeded = Some(true);
        let evidence = classify_tool_evidence(&failed).unwrap();

        assert_eq!(evidence.kind, EvidenceKind::Test);
        assert_eq!(evidence.verdict, EvidenceVerdict::Failed);
    }

    #[test]
    fn prose_without_objective_status_is_not_evidence() {
        let event = ObservedEvent {
            tool_name: "assistant_reflection".to_string(),
            output: "This solution worked well and appears successful".to_string(),
            ..ObservedEvent::default()
        };

        assert_eq!(classify_tool_evidence(&event), None);

        let unsupported_claim = ObservedEvent {
            output: "all tests passed".to_string(),
            succeeded: Some(true),
            ..event
        };
        assert_eq!(classify_tool_evidence(&unsupported_claim), None);
    }

    #[test]
    fn non_execution_tools_cannot_forge_verification_from_output_or_status() {
        for tool_name in ["read_file", "grep_files", "assistant_reflection", "exec"] {
            let forged = ObservedEvent {
                tool_name: tool_name.to_string(),
                command: Some("cargo test parser".to_string()),
                output: "test result: ok. 1 passed; 0 failed".to_string(),
                ..ObservedEvent::default()
            };

            assert_eq!(classify_tool_evidence(&forged), None, "tool: {tool_name}");
            assert_eq!(
                classify_tool_evidence(&ObservedEvent {
                    exit_code: Some(0),
                    succeeded: Some(true),
                    ..forged
                }),
                None,
                "tool with forged structured status: {tool_name}"
            );
        }
    }

    #[test]
    fn every_trusted_direct_execution_alias_requires_structured_status() {
        for tool_name in [
            "run_terminal_command",
            "run_terminal_cmd",
            "exec_command",
            "run_command",
            "bash",
            "shell",
        ] {
            let unverified = ObservedEvent {
                tool_name: tool_name.to_string(),
                command: Some("cargo test parser".to_string()),
                output: "test result: ok. 1 passed; 0 failed; exit code: 0".to_string(),
                ..ObservedEvent::default()
            };

            assert_eq!(
                classify_tool_evidence(&unverified),
                None,
                "tool without structured status: {tool_name}"
            );

            let verified = ObservedEvent {
                succeeded: Some(true),
                ..unverified
            };
            let evidence = classify_tool_evidence(&verified).unwrap();

            assert_eq!(evidence.kind, EvidenceKind::Test, "tool: {tool_name}");
            assert_eq!(evidence.verdict, EvidenceVerdict::Passed);
        }
    }

    #[test]
    fn successful_file_inspection_output_cannot_masquerade_as_verification() {
        for (command, output) in [
            (
                "cat test-results.txt",
                "test result: ok. 1 passed; 0 failed",
            ),
            ("cat build.log", "compilation failed: could not compile"),
            ("cat report.txt", "performance regression detected"),
        ] {
            let evidence = classify_tool_evidence(&event(command, output, 0, 1)).unwrap();

            assert_eq!(
                evidence.kind,
                EvidenceKind::CommandExit,
                "command: {command}"
            );
            assert!(!evidence.is_verification(), "command: {command}");
        }
    }

    #[test]
    fn trusted_tool_status_without_exit_code_is_evidence() {
        let event = ObservedEvent {
            tool_name: "run_command".to_string(),
            command: Some("pytest tests/test_parser.py".to_string()),
            succeeded: Some(true),
            timestamp: 7,
            ..ObservedEvent::default()
        };
        let evidence = classify_tool_evidence(&event).unwrap();

        assert_eq!(evidence.kind, EvidenceKind::Test);
        assert_eq!(evidence.verdict, EvidenceVerdict::Passed);
    }

    #[test]
    fn output_exit_code_text_without_structured_status_is_not_trusted() {
        let failed = ObservedEvent {
            tool_name: "bash".to_string(),
            command: Some("cargo check".to_string()),
            output: "{\"exit_code\": 2}".to_string(),
            ..ObservedEvent::default()
        };
        let passed = ObservedEvent {
            output: "exit code: 0".to_string(),
            ..failed.clone()
        };

        assert_eq!(classify_tool_evidence(&failed), None);
        assert_eq!(classify_tool_evidence(&passed), None);
    }

    #[test]
    fn structured_external_evaluator_signal_remains_non_objective() {
        let evaluator = ObservedEvent {
            tool_name: "external_evaluator".to_string(),
            command: Some("evaluate parser implementation".to_string()),
            succeeded: Some(true),
            timestamp: 7,
            ..ObservedEvent::default()
        };
        let evidence = classify_tool_evidence(&evaluator).unwrap();

        assert_eq!(evidence.kind, EvidenceKind::Judge);
        assert_eq!(evidence.verdict, EvidenceVerdict::Passed);
        assert!(!evidence.is_objective());

        assert_eq!(
            classify_tool_evidence(&ObservedEvent {
                succeeded: None,
                output: "evaluation passed".to_string(),
                ..evaluator
            }),
            None
        );
    }

    #[test]
    fn evidence_kind_distinguishes_independent_quality_dimensions() {
        let cases = [
            ("cargo test parser", EvidenceKind::Test),
            ("cargo check -p parser", EvidenceKind::Compile),
            ("cargo clippy --all-targets", EvidenceKind::Lint),
            ("mypy src", EvidenceKind::TypeCheck),
            ("cargo bench parser", EvidenceKind::Benchmark),
            ("git diff --check", EvidenceKind::Diff),
        ];

        for (command, expected) in cases {
            let evidence = classify_tool_evidence(&event(command, "ok", 0, 1)).unwrap();
            assert_eq!(evidence.kind, expected, "command: {command}");
        }
    }

    #[test]
    fn test_results_retain_partial_success_dimension() {
        let evidence = classify_tool_evidence(&event(
            "cargo test parser",
            "test result: FAILED. 8 passed; 2 failed",
            1,
            1,
        ))
        .unwrap();

        assert_eq!(evidence.verdict, EvidenceVerdict::Failed);
        assert_eq!(evidence.score, Some(0.8));
    }

    #[test]
    fn completed_runs_without_verification_produce_no_lessons() {
        let observation = observation(vec![ObservedEvent {
            tool_name: "assistant_reflection".to_string(),
            output: "Everything worked well".to_string(),
            ..ObservedEvent::default()
        }]);

        assert!(extract_experiences(&observation).is_empty());
    }

    #[test]
    fn successful_verified_run_produces_process_and_strategy_lessons() {
        let memories = extract_experiences(&observation(vec![event(
            "cargo test parser",
            "test result: ok. 4 passed; 0 failed",
            0,
            5,
        )]));

        assert_eq!(memories.len(), 2);
        assert!(
            memories
                .iter()
                .any(|memory| memory.category == ExperienceCategory::ToolProcessLesson)
        );
        let strategy = memories
            .iter()
            .find(|memory| memory.category == ExperienceCategory::SuccessfulPattern)
            .unwrap();
        assert_eq!(strategy.success, Some(true));
        assert_eq!(strategy.scope, ExperienceScope::ExactFile);
        assert_eq!(strategy.source_run_ids, vec!["run-42"]);
        assert_eq!(strategy.outcome.functional_correctness, Some(1.0));
        assert!(strategy.confidence <= 0.65);
        assert!(strategy.lesson.contains("existing AST visitor"));
    }

    #[test]
    fn inspection_lint_and_benchmark_alone_cannot_establish_successful_pattern() {
        for (command, output) in [
            ("git diff --check", "diff has no whitespace errors"),
            ("cargo clippy", "lint checks passed"),
            ("cargo bench parser", "benchmark completed"),
            (
                "cat test-results.txt",
                "test result: ok. 1 passed; 0 failed",
            ),
        ] {
            let memories = extract_experiences(&observation(vec![event(command, output, 0, 1)]));

            assert!(
                memories
                    .iter()
                    .all(|memory| memory.category != ExperienceCategory::SuccessfulPattern),
                "inspection-only command established implementation correctness: {command}"
            );
        }
    }

    #[test]
    fn functional_compile_and_type_verification_support_successful_patterns() {
        for (command, output) in [
            ("cargo test parser", "test result: ok. 1 passed; 0 failed"),
            ("cargo check -p parser", "finished checking parser"),
            ("mypy src", "success: no issues found"),
            ("runtime smoke", "runtime smoke passed"),
        ] {
            let memories = extract_experiences(&observation(vec![event(command, output, 0, 1)]));

            assert!(
                memories
                    .iter()
                    .any(|memory| memory.category == ExperienceCategory::SuccessfulPattern),
                "functional verification did not support implementation correctness: {command}"
            );
        }
    }

    #[test]
    fn extracted_evidence_records_sanitized_source_run_provenance() {
        let mut observation = observation(vec![event(
            "cargo test parser",
            "test result: ok. 4 passed; 0 failed",
            0,
            5,
        )]);
        observation.run_id = "run-42 refresh_token=hidden-source-token".to_string();
        let memories = extract_experiences(&observation);

        for memory in memories {
            for signal in memory.evidence.iter().chain(memory.test_results.iter()) {
                let source = signal.source_run_id.as_deref().unwrap();
                assert!(source.contains("run-42"));
                assert!(!source.contains("hidden-source-token"));
            }
        }
    }

    #[test]
    fn passing_lint_and_verification_do_not_fabricate_quality_or_completeness() {
        let memories = extract_experiences(&observation(vec![
            event("cargo clippy", "lint checks passed", 0, 1),
            event(
                "cargo test parser",
                "test result: ok. 4 passed; 0 failed",
                0,
                2,
            ),
        ]));

        for memory in memories {
            assert_eq!(memory.outcome.code_quality, None);
            assert_eq!(memory.outcome.completeness, None);
        }
    }

    #[test]
    fn process_lessons_stay_repository_scoped_while_patterns_keep_real_paths() {
        let memories = extract_experiences(&observation(vec![event(
            "cargo test parser",
            "test result: ok. 4 passed; 0 failed",
            0,
            1,
        )]));
        let process = memories
            .iter()
            .find(|memory| memory.category == ExperienceCategory::ToolProcessLesson)
            .unwrap();
        let pattern = memories
            .iter()
            .find(|memory| memory.category == ExperienceCategory::SuccessfulPattern)
            .unwrap();

        assert_eq!(process.scope, ExperienceScope::Repository);
        assert_eq!(pattern.scope, ExperienceScope::ExactFile);
        assert!(pattern.context.contains("src/parser/visitor.rs"));
        assert_eq!(
            observation_scope(&["".to_string()]),
            ExperienceScope::Repository
        );
    }

    #[test]
    fn failed_run_preserves_useful_partial_verification() {
        let mut observation = observation(vec![
            event(
                "cargo test parser",
                "test result: ok. 4 passed; 0 failed",
                0,
                1,
            ),
            event(
                "cargo build",
                "build failed: could not compile parser",
                1,
                2,
            ),
        ]);
        observation.completed = Some(false);
        let memories = extract_experiences(&observation);

        assert!(memories.iter().any(|memory| {
            memory.category == ExperienceCategory::ToolProcessLesson && memory.success == Some(true)
        }));
        assert!(memories.iter().any(|memory| {
            memory.category == ExperienceCategory::FailureAntiPattern
                && memory.success == Some(false)
        }));
        assert!(
            memories
                .iter()
                .all(|memory| memory.category != ExperienceCategory::SuccessfulPattern)
        );
    }

    #[test]
    fn generated_file_failures_create_specific_anti_patterns() {
        let memories = extract_experiences(&observation(vec![event(
            "cargo build",
            "build failed: generated file schema.rs is overwritten during build",
            1,
            3,
        )]));
        let failure = memories
            .iter()
            .find(|memory| memory.category == ExperienceCategory::FailureAntiPattern)
            .unwrap();

        assert!(failure.lesson.contains("generated files"));
        assert!(
            failure
                .recommendation
                .as_deref()
                .unwrap()
                .contains("generator")
        );
        assert!(failure.confidence <= 0.65);
    }

    #[test]
    fn proven_generated_file_behavior_emits_scoped_environmental_fact() {
        let memories = extract_experiences(&observation(vec![event(
            "cargo build",
            "build failed: generated file schema.rs is overwritten during build",
            1,
            3,
        )]));
        let fact = memories
            .iter()
            .find(|memory| memory.category == ExperienceCategory::EnvironmentalFact)
            .unwrap();
        let warning = memories
            .iter()
            .find(|memory| memory.category == ExperienceCategory::FailureAntiPattern)
            .unwrap();

        assert_eq!(fact.scope, ExperienceScope::Repository);
        assert_eq!(warning.scope, ExperienceScope::Repository);
        assert!(fact.lesson.contains("overwritten"));
        assert!(fact.evidence[0].is_objective());
    }

    #[test]
    fn generated_file_mention_without_proven_behavior_is_not_environmental_fact() {
        let memories = extract_experiences(&observation(vec![event(
            "cargo build",
            "build failed: generated file schema.rs has a syntax error",
            1,
            3,
        )]));

        assert!(
            memories
                .iter()
                .any(|memory| { memory.category == ExperienceCategory::FailureAntiPattern })
        );
        assert!(
            memories
                .iter()
                .all(|memory| { memory.category != ExperienceCategory::EnvironmentalFact })
        );
    }

    #[test]
    fn architectural_lessons_require_independently_verified_boundary() {
        let ordinary = extract_experiences(&observation(vec![event(
            "cargo test service_boundary",
            "test result: ok. 1 passed; 0 failed",
            0,
            1,
        )]));
        assert!(
            ordinary
                .iter()
                .all(|memory| { memory.category != ExperienceCategory::ArchitecturalLesson })
        );

        let verified = extract_experiences(&observation(vec![event(
            "cargo test service_boundary",
            "service boundary verified: flags resolve before client dispatch",
            0,
            1,
        )]));
        let architecture = verified
            .iter()
            .find(|memory| memory.category == ExperienceCategory::ArchitecturalLesson)
            .unwrap();

        assert_eq!(architecture.scope, ExperienceScope::Repository);
        assert!(architecture.lesson.contains("service boundary verified"));
    }

    #[test]
    fn uncertainty_requires_unresolved_contradictory_objective_results() {
        let contradictory = extract_experiences(&observation(vec![
            event(
                "cargo test parser",
                "test result: ok. 1 passed; 0 failed",
                0,
                1,
            ),
            event("cargo test parser", "test failed: assertion failed", 1, 2),
        ]));
        let hypothesis = contradictory
            .iter()
            .find(|memory| memory.category == ExperienceCategory::UncertainHypothesis)
            .unwrap();

        assert_eq!(hypothesis.evidence.len(), 2);
        assert_eq!(hypothesis.success, None);
        assert!(hypothesis.confidence <= 0.55);

        let resolved = extract_experiences(&observation(vec![
            event("cargo test parser", "test failed: assertion failed", 1, 1),
            event(
                "cargo test parser",
                "test result: ok. 1 passed; 0 failed",
                0,
                2,
            ),
        ]));
        assert!(
            resolved
                .iter()
                .all(|memory| { memory.category != ExperienceCategory::UncertainHypothesis })
        );
    }

    #[test]
    fn database_lock_failures_recommend_serialization() {
        let memories = extract_experiences(&observation(vec![event(
            "cargo test migrations",
            "test failed: database is locked",
            1,
            3,
        )]));

        assert!(memories[0].lesson.contains("lock contention"));
        assert!(
            memories[0]
                .recommendation
                .as_deref()
                .unwrap()
                .contains("Serialize")
        );
    }

    #[test]
    fn unresolved_failure_blocks_successful_strategy_even_if_completed() {
        let memories = extract_experiences(&observation(vec![
            event(
                "cargo test parser",
                "test result: ok. 4 passed; 0 failed",
                0,
                1,
            ),
            event("cargo clippy", "lint failed: unused import", 1, 2),
        ]));

        assert!(
            memories
                .iter()
                .all(|memory| memory.category != ExperienceCategory::SuccessfulPattern)
        );
    }

    #[test]
    fn bounded_events_retain_final_failure_after_obsolete_success_prefix() {
        let mut events: Vec<ObservedEvent> = (0..MAX_OBSERVED_EVENTS)
            .map(|index| {
                event(
                    "cargo test parser",
                    "test result: ok. 1 passed; 0 failed",
                    0,
                    index as i64,
                )
            })
            .collect();
        events.push(event(
            "cargo test parser",
            "test failed: final verification failed",
            1,
            MAX_OBSERVED_EVENTS as i64,
        ));

        assert!(events.len() >= 129);

        let memories = extract_experiences(&observation(events));

        assert!(
            memories
                .iter()
                .any(|memory| memory.category == ExperienceCategory::FailureAntiPattern)
        );
        assert!(
            memories
                .iter()
                .all(|memory| memory.category != ExperienceCategory::SuccessfulPattern)
        );
    }

    #[test]
    fn bounded_events_retain_final_repair_after_obsolete_failure_prefix() {
        let mut events: Vec<ObservedEvent> = (0..MAX_OBSERVED_EVENTS)
            .map(|index| {
                event(
                    "cargo test parser",
                    "test failed: assertion failed",
                    1,
                    index as i64,
                )
            })
            .collect();
        events.push(event(
            "cargo test parser",
            "test result: ok. 1 passed; 0 failed",
            0,
            MAX_OBSERVED_EVENTS as i64,
        ));

        assert!(events.len() >= 129);

        let memories = extract_experiences(&observation(events));

        assert!(
            memories
                .iter()
                .any(|memory| memory.category == ExperienceCategory::FailureAntiPattern)
        );
        assert!(
            memories
                .iter()
                .any(|memory| memory.category == ExperienceCategory::SuccessfulPattern)
        );
    }

    #[test]
    fn repaired_failure_can_support_later_verified_strategy() {
        let memories = extract_experiences(&observation(vec![
            event("cargo test parser", "test failed: assertion failed", 1, 1),
            event(
                "cargo test parser",
                "test result: ok. 4 passed; 0 failed",
                0,
                2,
            ),
        ]));

        assert!(
            memories
                .iter()
                .any(|memory| memory.category == ExperienceCategory::FailureAntiPattern)
        );
        assert!(
            memories
                .iter()
                .any(|memory| memory.category == ExperienceCategory::SuccessfulPattern)
        );
    }

    #[test]
    fn negative_judge_feedback_prevents_strong_positive_memory() {
        let mut observation = observation(vec![event(
            "cargo test parser",
            "test result: ok. 4 passed; 0 failed",
            0,
            1,
        )]);
        observation.judge_feedback = Some("Rejected: poor quality and brittle design".to_string());
        let memories = extract_experiences(&observation);

        assert!(
            memories
                .iter()
                .all(|memory| memory.category != ExperienceCategory::SuccessfulPattern)
        );
        assert!(
            memories
                .iter()
                .any(|memory| memory.category == ExperienceCategory::ToolProcessLesson)
        );
    }

    #[test]
    fn scope_starts_specific_and_never_assumes_global_applicability() {
        assert_eq!(observation_scope(&[]), ExperienceScope::Repository);
        assert_eq!(
            observation_scope(&["src/parser.rs".to_string()]),
            ExperienceScope::ExactFile
        );
        assert_eq!(
            observation_scope(&[
                "src/parser/ast.rs".to_string(),
                "src/parser/visitor.rs".to_string(),
            ]),
            ExperienceScope::Module
        );
        assert_eq!(
            observation_scope(&["src/parser.rs".to_string(), "tests/parser.rs".to_string()]),
            ExperienceScope::Repository
        );
    }

    #[test]
    fn secrets_are_redacted_from_all_persisted_experience_fields() {
        let mut observation = observation(vec![event(
            "cargo test --token cli-secret XAI_API_KEY=sk-live-secret https://api.test?q=x&token=query-secret",
            "error: Authorization: Bearer bearer-secret ghp_githubsecret",
            1,
            1,
        )]);
        observation.strategy = "Use API_KEY=strategy-secret".to_string();
        observation.key_decisions = vec!["--password decision-secret".to_string()];
        observation.judge_feedback = Some("api_key: feedback-secret".to_string());
        let memories = extract_experiences(&observation);
        let serialized = serde_json::to_string(&memories).unwrap();

        for secret in [
            "cli-secret",
            "sk-live-secret",
            "query-secret",
            "bearer-secret",
            "ghp_githubsecret",
            "strategy-secret",
            "decision-secret",
            "feedback-secret",
        ] {
            assert!(!serialized.contains(secret), "persisted secret: {secret}");
        }

        assert!(serialized.contains("[REDACTED]"));
    }

    #[test]
    fn raw_outputs_are_capped_and_never_persisted_as_trajectories() {
        let raw_output = format!("test failed: {}", "RAW_TRAJECTORY ".repeat(200));
        let memories = extract_experiences(&observation(vec![event(
            "cargo test parser",
            &raw_output,
            1,
            1,
        )]));

        for memory in &memories {
            assert!(memory.lesson.chars().count() <= MAX_STORED_TEXT_CHARS);
            assert!(
                memory
                    .evidence
                    .iter()
                    .all(|signal| signal.summary.chars().count() <= MAX_STORED_TEXT_CHARS)
            );
        }

        let serialized = serde_json::to_string(&memories).unwrap();
        assert!(serialized.len() < raw_output.len() * 2);
        assert!(!serialized.contains(&raw_output));
    }

    #[test]
    fn duplicate_failures_and_verifications_are_consolidated_per_run() {
        let mut observation = observation(vec![
            event("cargo test parser", "test failed: assertion failed", 1, 1),
            event(
                "cargo test parser",
                "test failed: assertion failed again",
                1,
                2,
            ),
            event(
                "cargo test parser",
                "test result: ok. 4 passed; 0 failed",
                0,
                3,
            ),
            event(
                "cargo test parser",
                "test result: ok. 4 passed; 0 failed",
                0,
                4,
            ),
        ]);
        observation.completed = Some(false);
        let memories = extract_experiences(&observation);

        assert_eq!(
            memories
                .iter()
                .filter(|memory| memory.category == ExperienceCategory::FailureAntiPattern)
                .count(),
            1
        );
        assert_eq!(
            memories
                .iter()
                .filter(|memory| memory.category == ExperienceCategory::ToolProcessLesson)
                .count(),
            1
        );
    }

    #[test]
    fn unicode_summaries_are_truncated_at_character_boundaries() {
        let output = format!("test failed: {}", "🦀".repeat(400));
        let evidence = classify_tool_evidence(&event("cargo test", &output, 1, 1)).unwrap();

        assert_eq!(evidence.summary.chars().count(), MAX_STORED_TEXT_CHARS);
        assert!(evidence.summary.ends_with('…'));
    }

    #[test]
    fn shared_redaction_covers_cookies_url_credentials_and_json_secrets() {
        let input = concat!(
            "Cookie: session=hidden-cookie; csrftoken=hidden-csrf ",
            "https://alice:hidden-password@example.test/private ",
            r#"{"refresh_token":"hidden-refresh","password":"hidden-json-password","api_key":"hidden-api"}"#,
            " Authorization: Bearer hidden-bearer"
        );
        let sanitized = redact_sensitive_text(input);

        for secret in [
            "hidden-cookie",
            "hidden-csrf",
            "hidden-password",
            "hidden-refresh",
            "hidden-json-password",
            "hidden-api",
            "hidden-bearer",
        ] {
            assert!(!sanitized.contains(secret), "leaked {secret}: {sanitized}");
        }

        assert!(sanitized.contains("example.test"));
        assert!(sanitized.contains("[REDACTED]"));
    }

    #[test]
    fn sensitive_field_names_cover_opaque_provider_variants_without_project_names() {
        for field in [
            "token",
            "secret",
            "credential",
            "credentials",
            "password",
            "openai_token",
            "xai-secret",
            "providerCredential",
            "providerPassword",
            "X-Api-Key",
            "X-Auth-Token",
            "Proxy-Authorization",
            "Set-Cookie",
            "AWS_SECRET_ACCESS_KEY",
            "AWS_ACCESS_KEY_ID",
            "AWS_SESSION_TOKEN",
            "AWS_SECURITY_TOKEN",
            "aws-secret-access-key",
            "aws.access.key.id",
            "awsSecretAccessKey",
            "awsAccessKeyId",
            "secretAccessKey",
            "accessKeyId",
        ] {
            assert!(
                is_sensitive_field_name(field),
                "unrecognized secret field: {field}"
            );
        }

        for field in [
            "name",
            "project_name",
            "repository_id",
            "xai-grok",
            "xai-grok-memory",
            "xai-grok-shell",
            "headers",
            "content-type",
            "AWS_REGION",
            "AWS_DEFAULT_REGION",
            "AWS_PROFILE",
            "aws-region",
            "awsProfile",
            "project_id",
        ] {
            assert!(
                !is_sensitive_field_name(field),
                "over-redacted project field: {field}"
            );
        }
    }

    #[test]
    fn shared_redaction_covers_nested_opaque_json_secrets_and_headers() {
        let input = concat!(
            r#"{"project":"xai-grok-memory","payload":{"token":"opaque-one","secret":"opaque-two","credential":"opaque-three","password":"opaque-four","openai_token":"opaque-five","providerCredential":"opaque-six"},"headers":{"Authorization":"opaque-seven","X-Api-Key":"opaque-eight","X-Auth-Token":"opaque-nine","Content-Type":"application/json"},"nested":[{"provider_secret":"opaque-ten"}],"credential_bundle":{"first":"opaque-eleven","second":"opaque-twelve"}}"#,
            " X-Api-Key: opaque-thirteen Authorization: Bearer opaque-fourteen"
        );
        let sanitized = redact_sensitive_text(input);

        for secret in [
            "opaque-one",
            "opaque-two",
            "opaque-three",
            "opaque-four",
            "opaque-five",
            "opaque-six",
            "opaque-seven",
            "opaque-eight",
            "opaque-nine",
            "opaque-ten",
            "opaque-eleven",
            "opaque-twelve",
            "opaque-thirteen",
            "opaque-fourteen",
        ] {
            assert!(!sanitized.contains(secret), "leaked {secret}: {sanitized}");
        }

        assert!(sanitized.contains("xai-grok-memory"));
        assert!(sanitized.contains("application/json"));
        assert!(sanitized.contains("[REDACTED]"));
    }

    #[test]
    fn aws_credentials_are_redacted_across_assignments_headers_and_nested_json() {
        let input = concat!(
            "AWS_SECRET_ACCESS_KEY=actual-secret ",
            "AWS_ACCESS_KEY_ID='quoted access identifier' ",
            "AWS_SESSION_TOKEN=\"quoted session credential\" ",
            "AWS_SECURITY_TOKEN=security-credential ",
            "--aws-secret-access-key=cli-secret ",
            "--aws-access-key-id cli-access-id ",
            "AWS-Session-Token: header-session ",
            r#"{"outer":{"awsSecretAccessKey":"json-secret","accessKeyId":"json-access","AWS_SECURITY_TOKEN":{"nested":"nested-security"}},"AWS_REGION":"us-west-2","awsProfile":"development","project_id":"ordinary-project"}"#,
            " AWS_PROFILE=production AWS_DEFAULT_REGION=eu-west-1"
        );
        let sanitized = redact_sensitive_text(input);

        for secret in [
            "actual-secret",
            "quoted access identifier",
            "quoted session credential",
            "security-credential",
            "cli-secret",
            "cli-access-id",
            "header-session",
            "json-secret",
            "json-access",
            "nested-security",
        ] {
            assert!(!sanitized.contains(secret), "leaked {secret}: {sanitized}");
        }

        for ordinary_value in [
            "us-west-2",
            "development",
            "ordinary-project",
            "production",
            "eu-west-1",
        ] {
            assert!(
                sanitized.contains(ordinary_value),
                "over-redacted {ordinary_value}: {sanitized}"
            );
        }
    }

    #[test]
    fn aws_credentials_never_persist_in_serialized_extracted_experiences() {
        let mut observation = observation(vec![event(
            "AWS_SECRET_ACCESS_KEY='command secret value' AWS_ACCESS_KEY_ID=command-access cargo test",
            r#"test failed: {"nested":{"awsSessionToken":"output-session","AWS_SECURITY_TOKEN":{"value":"output-security"}}}"#,
            1,
            1,
        )]);
        observation.strategy = "--aws-secret-access-key strategy-secret".to_string();
        observation.key_decisions = vec!["AWS-Access-Key-Id: decision-access".to_string()];
        observation.environment = concat!(
            r#"{"secretAccessKey":"environment-secret","AWS_REGION":"us-east-1","AWS_PROFILE":"development"}"#
        )
        .to_string();
        observation.judge_feedback = Some("AWS_SESSION_TOKEN=feedback-session".to_string());

        let memories = extract_experiences(&observation);
        assert!(!memories.is_empty());
        let serialized = serde_json::to_string(&memories).unwrap();

        for secret in [
            "command secret value",
            "command-access",
            "output-session",
            "output-security",
            "strategy-secret",
            "decision-access",
            "environment-secret",
            "feedback-session",
        ] {
            assert!(!serialized.contains(secret), "persisted secret: {secret}");
        }

        assert!(serialized.contains("us-east-1"));
        assert!(serialized.contains("development"));
        assert!(serialized.contains("[REDACTED]"));
    }

    #[test]
    fn opaque_json_secrets_never_persist_in_extracted_experience_fields() {
        let mut observation = observation(vec![event(
            "cargo test --credential opaque-command",
            r#"test failed: {"token":"opaque-output","payload":{"credential":"opaque-nested"}}"#,
            1,
            1,
        )]);
        observation.strategy =
            r#"{"project":"xai-grok-memory","secret":"opaque-strategy"}"#.to_string();
        observation.key_decisions = vec![
            r#"{"headers":{"X-Api-Key":"opaque-header","Authorization":"opaque-auth"}}"#
                .to_string(),
        ];
        observation.environment = r#"{"password":"opaque-password"}"#.to_string();

        let serialized = serde_json::to_string(&extract_experiences(&observation)).unwrap();

        for secret in [
            "opaque-command",
            "opaque-output",
            "opaque-nested",
            "opaque-strategy",
            "opaque-header",
            "opaque-auth",
            "opaque-password",
        ] {
            assert!(!serialized.contains(secret), "persisted secret: {secret}");
        }

        assert!(serialized.contains("xai-grok-memory"));
    }

    #[test]
    fn shared_redaction_removes_complete_and_unterminated_private_keys() {
        let complete = concat!(
            "prefix -----BEGIN RSA PRIVATE KEY-----\n",
            "hidden-private-material\n",
            "-----END RSA PRIVATE KEY----- suffix"
        );
        let unterminated = "-----BEGIN OPENSSH PRIVATE KEY-----\nhidden-unterminated";

        assert!(!redact_sensitive_text(complete).contains("hidden-private-material"));
        assert!(!redact_sensitive_text(unterminated).contains("hidden-unterminated"));
        assert!(redact_sensitive_text(complete).contains("suffix"));
    }

    #[test]
    fn shared_redaction_preserves_project_names_and_caps_output() {
        let text = format!(
            "xai-grok xai-grok-memory xai-grok-shell {}",
            "safe ".repeat(10_000)
        );
        let sanitized = redact_sensitive_text(&text);

        assert!(sanitized.contains("xai-grok xai-grok-memory xai-grok-shell"));
        assert!(sanitized.chars().count() <= MAX_REDACTED_TEXT_CHARS);
    }
}
